### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sidarylko** [christofsteel/syng#1]
though i'm a newbie and i've tried to install but having a hard time. i followed the instructions and it doesnt show where im gonna access the UI after i installed with no errors.

**Comment by christofsteel** [comment]
You most likely installed it via the `pip install` command with the `[client]` option. I recommend installing the software into a dedicated virtualenv to avoid mixing the required python dependencies with your system packages, but this is not strictly necessary.
You should now be able to launch the gui using the `syng-gui` command in the terminal. Currently there is no `.desktop` file generated, so you won't find an entry in your application launcher.

I will keep this Issue open, if you have any further questions and close it in a week or so.

**Comment by christofsteel** [comment]
Since today, there exists a flatpak, that should ease the installation process significantly.
